Periodically send rnode mmaps sizes to InfluxDB

diff --git a/rundeck-scripts/start-node b/rundeck-scripts/start-node
--- a/rundeck-scripts/start-node
+++ b/rundeck-scripts/start-node
@@ -167,6 +167,13 @@ while (( i )); do
 	if [[ -n "$container_id" ]]; then
 		echo "RNode is running"
 		nohup docker logs -f $container_id &> $DIAG_DIR/console.log &
+
+                node_pid="$(docker inspect -f '{{.State.Pid}}' rnode || echo 0)"
+                if (( node_pid == 0 )); then
+                        echo "Could not get node PID"
+                        break
+                fi
+                nohup ./pmap.py "$node_pid" "perf-bootstrap.c.developer-222401.internal" 8091 testnet1 &
 		break
 	fi
 
